name: Deployment

on:
  deployment:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - run: cat ${{ github.event_path }}
      - name: Tweet
        uses: snow-actions/tweet@v1.1.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            Twitter API が更新されました
            https://snowcait.github.io/twitter-swagger-ui/
